[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/exp1.1/exp 1_1.html"
  status = 200

[[redirects]]
  from = "/exp1.1"
  to = "/exp1.1/exp 1_1.html"
  status = 200

[[redirects]]
  from = "/exp1.2"
  to = "/exp1.2/exp1_2.html"
  status = 200

[[redirects]]
  from = "/exp1.3"
  to = "/exp1.3/index.html"
  status = 200

